ad_site_homepage:
    path:     /hello/{name}
    defaults: { _controller: AdSiteBundle:Default:index }

test_login:
    path:     /login
    defaults : { _controller: AdSiteBundle:Login:login}

test_homepage:
    path:     /welcome
    defaults : { _controller: AdSiteBundle:Welcome:welcome}

add_article:
    path:      /addarticle
    defaults : { _controller: AdSiteBundle:NewArticle:AddArticle}