ad_site_homepage:
    path:     /hello/{name}
    defaults: { _controller: AdSiteBundle:Default:index }

test:
    path:     /login
    defaults : { _controller: AdSiteBundle:Login:login}

test_homepage:
    path:     /welcome
    defaults : { _controller: AdSiteBundle:Welcome:welcome}