<?php

namespace AdSite\AdSiteBundle\Repository;

/**
 * ArticlesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticlesRepository extends \Doctrine\ORM\EntityRepository
{
    public function getArticlesByCategory($category){
        $articles = $this->getEntityManager()->createQuery('
        SELECT a FROM AdSiteBundle:Articles a
        WHERE a.category LIKE :category
        ')->setParameter('category', '%'.$category.'%')->getResult();

        return $articles;
    }


    public function getArticlesByUserId($userId){
        $articles = $this->getEntityManager()->createQuery('
        SELECT a FROM AdSiteBundle:Articles a
        WHERE a.userId = :userId
        ')->setParameter('userId', '%'.$userId.'%')->getResult();

        return $articles;
    }
}
