<?php

namespace AdSite\AdSiteBundle\Repository;

/**
 * PicturesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PicturesRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPicturesByArticle($idArticle){
        $pictures = $this->getEntityManager()->createQuery('
        SELECT a FROM AdSiteBundle:Pictures a
        WHERE EXISTS ( SELECT b FROM AdSiteBundle:Articles b 
        WHERE b.idArticle = :idArticle)
        ')->setParameters(array('idArticle' => $idArticle))->getResult();

        return $pictures;
    }

    public function getPicturesById($id){
        $pictures = $this->getEntityManager()->createQuery('
        SELECT a FROM AdSiteBundle:Pictures a
        WHERE a.id = :id
        ')->setParameter('id', '%'.$id.'%')->getResult();

        return $pictures;
    }
}
