<?php

namespace AdSite\AdSiteBundle\Repository;

/**
 * PicturesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PicturesRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPicturesByArticle($idArticle){
        $pictures = $this->getEntityManager()->createQuery('
        SELECT a FROM AdSiteBundle:Pictures a
        WHERE a.id_article = :idArticle
        ')->setParameter('idArticle', '%'.$idArticle.'%')->getResult();

        return $pictures;
    }
}
